version: '2'
services:
  zookeeper:
    image: nrt17.azurecr.io/nrt17/zookeeper:0.1
    container_name: zk1
    hostname: zk1
    ports:
      - "34050:2181"
    networks:
      - nrt17net
  kafka1:
    image: nrt17.azurecr.io/nrt17/kafka:0.1
    container_name: ks1
    hostname: ks1
    ports:
      - "34001:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 1      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nrt17net
  kafka2:
    image: nrt17.azurecr.io/nrt17/kafka:0.1
    container_name: ks2
    hostname: ks2
    ports:
      - "34002:9092"
    depends_on:
      - zookeeper
      - kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 2     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nrt17net
  kafka3:
    image: nrt17.azurecr.io/nrt17/kafka:0.1
    container_name: ks3
    hostname: ks3
    ports:
      - "34003:9092"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_CREATE_TOPICS: "inputtopic:16:3,outputtopic:16:3,debugtopic:16:3"
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 3      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nrt17net
  flink-master:
    image: nrt17.azurecr.io/nrt17/flinkmaster:0.1
    ports:
      - "34010:8081"
      - "34011:6123"
    container_name: flink-master
    hostname: flink-master
    networks:
      - nrt17net
  flink-worker1:
    image: nrt17.azurecr.io/nrt17/flinkworker:0.1
    ports:
      - "34012:6121"
      - "34013:6122"
    container_name: flink-worker1
    hostname: flink-worker1
    networks:
      - nrt17net
  flink-worker2:
    image: nrt17.azurecr.io/nrt17/flinkworker:0.1
    ports:
      - "34014:6121"
      - "34015:6122"
    container_name: flink-worker2
    hostname: flink-worker2
    networks:
      - nrt17net
  sparkm1:
    image: nrt17.azurecr.io/nrt17/sparkmaster:0.3
    container_name: sparkm1
    hostname: sparkm1
    command: spark-class org.apache.spark.deploy.master.Master -h sparkm1
    environment:
      MASTER: spark://sparkm1:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      KAFKA_ADVERTISED_SERVERS: "ks1:9092,ks2:9092,ks3:9092"
    ports:
      - 34101:4040
      - 34102:6066
      - 34103:7001
      - 34104:7002
      - 34105:7003
      - 34106:7004
      - 34107:7005
      - 34108:7006
      - 34109:7077
      - 34110:8080
    volumes:
      - /$NRT17_HOME/dockervolumesforcache/sparkhdfs:/clustervolume
    networks:
      - nrt17net
  sparkw1:
    image: nrt17.azurecr.io/nrt17/sparkworker:0.1
    container_name: sparkw1
    hostname: sparkw1
    command: spark-class org.apache.spark.deploy.worker.Worker spark://sparkm1:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      KAFKA_ADVERTISED_SERVERS: "ks1:9092,ks2:9092,ks3:9092"
    depends_on:
      - sparkm1
    ports:
      - 34120:7012
      - 34121:7013
      - 34122:7014
      - 34123:7015
      - 34124:7016
      - 34125:8881
      - 34126:8081
    volumes:
      - /$NRT17_HOME/dockervolumesforcache/sparkhdfs:/clustervolume
    networks:
      - nrt17net
  sparkw2:
    image: nrt17.azurecr.io/nrt17/sparkworker:0.1
    container_name: sparkw2
    hostname: sparkw2
    command: spark-class org.apache.spark.deploy.worker.Worker spark://sparkm1:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      KAFKA_ADVERTISED_SERVERS: "ks1:9092,ks2:9092,ks3:9092"
    depends_on:
      - sparkm1
    ports:
      - 34130:7012
      - 34131:7013
      - 34132:7014
      - 34133:7015
      - 34134:7016
      - 34135:8881
      - 34136:8081
    volumes:
      - /$NRT17_HOME/dockervolumesforcache/sparkhdfs:/clustervolume
    networks:
      - nrt17net
networks:
  nrt17net:
    driver: bridge
